2025-03-27 12:35:19,000 WARNING django.security: SuspiciousOperation: Invalid HTTP_HOST header
2025-03-27 12:10:18,000 DEBUG django.db.backends: (0.43) SELECT * FROM 'cart' WHERE id = 11;
2025-03-27 12:26:18,000 WARNING django.security: ConnectionError: Failed to connect to payment gateway
2025-03-27 12:20:50,000 DEBUG django.db.backends: (0.14) SELECT * FROM 'reviews' WHERE id = 76;
2025-03-27 12:33:05,000 ERROR django.request: Internal Server Error: /api/v1/users/ [192.168.1.39] - PermissionDenied: User does not have permission
2025-03-27 12:29:35,000 INFO django.request: GET /api/v1/orders/ 204 OK [192.168.1.67]
2025-03-27 12:06:15,000 WARNING django.security: IntegrityError: duplicate key value violates unique constraint
2025-03-27 12:10:49,000 CRITICAL django.core.management: OSError: No space left on device
2025-03-27 12:42:07,000 INFO django.request: GET /api/v1/users/ 201 OK [192.168.1.22]
2025-03-27 12:44:47,000 INFO django.request: GET /api/v1/payments/ 204 OK [192.168.1.57]
2025-03-27 12:05:14,000 INFO django.request: GET /api/v1/auth/login/ 200 OK [192.168.1.28]
2025-03-27 12:18:30,000 CRITICAL django.core.management: ValueError: Invalid input data
2025-03-27 12:13:15,000 INFO django.request: GET /api/v1/products/ 201 OK [192.168.1.72]
2025-03-27 12:44:40,000 INFO django.request: GET /api/v1/auth/login/ 200 OK [192.168.1.47]
2025-03-27 12:41:43,000 DEBUG django.db.backends: (0.46) SELECT * FROM 'payments' WHERE id = 92;
2025-03-27 12:22:35,000 ERROR django.request: Internal Server Error: /api/v1/users/ [192.168.1.90] - DatabaseError: Deadlock detected
2025-03-27 12:33:37,000 INFO django.request: GET /api/v1/reviews/ 204 OK [192.168.1.15]
2025-03-27 12:08:12,000 INFO django.request: GET /api/v1/reviews/ 200 OK [192.168.1.57]
2025-03-27 12:36:16,000 INFO django.request: GET /api/v1/products/ 204 OK [192.168.1.29]
2025-03-27 12:14:56,000 DEBUG django.db.backends: (0.17) SELECT * FROM 'support' WHERE id = 39;
2025-03-27 12:07:35,000 INFO django.request: GET /api/v1/support/ 200 OK [192.168.1.23]
2025-03-27 12:22:08,000 CRITICAL django.core.management: OSError: No space left on device
2025-03-27 12:01:37,000 INFO django.request: GET /admin/dashboard/ 201 OK [192.168.1.12]
2025-03-27 12:33:11,000 INFO django.request: GET /api/v1/shipping/ 200 OK [192.168.1.86]
2025-03-26 12:40:33,000 DEBUG django.db.backends: (0.46) SELECT * FROM 'users' WHERE id = 51;
2025-03-26 12:12:52,000 WARNING django.security: DatabaseError: Deadlock detected
2025-03-26 12:27:11,000 INFO django.request: GET /api/v1/checkout/ 201 OK [192.168.1.13]
2025-03-26 12:30:43,000 ERROR django.request: Internal Server Error: /api/v1/reviews/ [192.168.1.95] - DatabaseError: Deadlock detected
2025-03-26 12:29:25,000 INFO django.request: GET /api/v1/auth/login/ 200 OK [192.168.1.27]
2025-03-26 12:00:11,000 INFO django.request: GET /api/v1/shipping/ 200 OK [192.168.1.48]
2025-03-26 12:05:59,000 INFO django.request: GET /api/v1/reviews/ 204 OK [192.168.1.24]
2025-03-26 12:24:21,000 WARNING django.security: DatabaseError: Deadlock detected
2025-03-26 12:17:15,000 INFO django.request: GET /api/v1/support/ 200 OK [192.168.1.29]
2025-03-26 12:47:25,000 INFO django.request: GET /api/v1/support/ 201 OK [192.168.1.88]
2025-03-26 12:43:27,000 INFO django.request: GET /api/v1/payments/ 200 OK [192.168.1.69]
2025-03-26 12:33:26,000 WARNING django.security: OSError: No space left on device
2025-03-26 12:06:48,000 ERROR django.request: Internal Server Error: /api/v1/checkout/ [192.168.1.32] - SuspiciousOperation: Invalid HTTP_HOST header
2025-03-26 12:18:31,000 INFO django.request: GET /admin/login/ 200 OK [192.168.1.46]
2025-03-26 12:34:20,000 WARNING django.security: SuspiciousOperation: Invalid HTTP_HOST header
2025-03-26 12:17:58,000 DEBUG django.db.backends: (0.10) SELECT * FROM 'users' WHERE id = 54;
2025-03-26 12:10:14,000 ERROR django.request: Internal Server Error: /api/v1/reviews/ [192.168.1.80] - ValueError: Invalid input data
2025-03-26 12:44:56,000 INFO django.request: GET /api/v1/support/ 201 OK [192.168.1.25]